name: build
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: firmware
      run: |
        git clone https://github.com/remixgithub/padavan_test.git
        git clone https://gitlab.com/hadzhioglu/padavan-ng.git
        cp -a padavan_test/padavan-ng/. padavan-ng/
        mv padavan-ng/trunk/r3g.config padavan-ng/trunk/.config
        cd padavan-ng
        git config user.email anon@anon.anon
        git revert e076679ce081c2cedc3450b5933f995e910f1760 --no-edit
        git revert b6129b5502851bfabe6b0700219072cdf34effcf --no-edit
        chmod +x dl_toolchain.sh
        ./dl_toolchain.sh
        cd trunk
        ./build_firmware.sh
    - uses: actions/upload-artifact@v3
      with:
        name: padavan_firmware
        path: padavan-ng/trunk/images
